version: "3"
services:
  web:
    platform: linux/amd64
    build: .
    ports:
      - "7080:3000"
    volumes:
      - .:/src/backend
    depends_on:
      mysql:
        condition: service_started

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./data/db:/data/db
