version: "3"

services:
  web:
    build: ./backend

    ports:
      - "7080:3000"
    depends_on:
      mysql:
        condition: service_started

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./data/db:/data/db
